p={'t1':20,'a':100,'t2':'rays'}
print(p,type(p))
# print(p['a'])
# print(p.get('a'))
# print(p.items())
# print(p.keys())
# print(p.values())
p.update({'t5':'soft','t6':'129'})
print(p)
# p.clear()
# q=p.clear()
# q=p.pop('t2')
q=p.popitem()
print(p)
print(q)