p={12,2,1,'mango',30,'rays',4}
print(p,type(p))
# q=p.add(50)
# q=p.update([2,9,21])
# q=p.clear()
# q=p.remove(35)
# q=p.discard(35)
# q=p.pop()
k={32,9,4,'mango'}
# q=p.union(k)
# q=p.update(p.union(k))
# q=p.intersection(k)
# q=p.intersection_update(k)
# q=p.difference(k)
# q=p.difference_update(k)
# q=p.symmetric_difference(k)
q=p.symmetric_difference_update(k)
print(p)
print(k)
print(q)